#!/usr/bin/env python3
import html, json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DATA=ROOT/'data'/'items.json'; OUT=ROOT/'public'/'index.html'
LABEL={'domestic':'국내','global':'해외'}
def esc(x): return html.escape(str(x or ''))
def badge(x,c=''):
    return '' if not x else f'<span class="badge {c}">{esc(x)}</span>'
def card(i):
    ticks=''.join(badge(t,'ticker') for t in i.get('tickers',[]))
    url=i.get('url') or ''
    link=f'<a class="source-link" href="{esc(url)}" target="_blank" rel="noreferrer">원문</a>' if url else ''
    when=i.get('published_at') or i.get('collected_at') or ''
    return f'''<article class="card"><div class="meta"><strong>{esc(i.get('source','출처 미상'))}</strong><span>{esc(when)}</span>{link}</div><h3>{esc(i.get('title','제목 없음'))}</h3><p>{esc(i.get('summary',''))}</p><div class="badges">{badge(i.get('recommendation','정보'),'rec')}{badge(i.get('confidence',''),'conf')}{ticks}</div></article>'''
def section(region,items):
    body='\n'.join(card(i) for i in items if i.get('region')==region) or '<p class="empty">아직 수집된 항목이 없습니다.</p>'
    return f'<section id="{region}" class="tabpanel"><h2>{LABEL[region]} 정보</h2>{body}</section>'
def main():
    items=json.loads(DATA.read_text(encoding='utf-8')) if DATA.exists() else []
    generated=datetime.now().strftime('%Y-%m-%d %H:%M')
    doc=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Stock Info Dashboard</title><style>:root{{--panel:#121a33;--panel2:#182442;--text:#eef3ff;--muted:#9fb0d0;--accent:#65d6ff;--green:#89f7a5;--yellow:#ffe08a}}*{{box-sizing:border-box}}body{{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:linear-gradient(135deg,#081020,#111a35);color:var(--text)}}header{{padding:32px 22px 18px;max-width:1100px;margin:auto}}h1{{margin:0 0 8px;font-size:clamp(28px,5vw,48px)}}.subtitle{{color:var(--muted)}}.tabs{{display:flex;gap:10px;max-width:1100px;margin:0 auto 16px;padding:0 22px}}.tabs a{{text-decoration:none;color:var(--text);background:var(--panel);border:1px solid #26385f;padding:10px 18px;border-radius:999px}}main{{max-width:1100px;margin:auto;padding:0 22px 60px}}.tabpanel{{margin:18px 0 34px}}h2{{color:var(--accent)}}.card{{background:rgba(18,26,51,.92);border:1px solid #26385f;border-radius:18px;padding:18px;margin:14px 0;box-shadow:0 12px 32px rgba(0,0,0,.25)}}.card h3{{margin:8px 0;font-size:21px}}.card p{{color:#d9e4ff;line-height:1.58}}.meta{{display:flex;flex-wrap:wrap;gap:10px;color:var(--muted);font-size:14px}}.source-link{{color:var(--accent)}}.badges{{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}}.badge{{display:inline-flex;padding:5px 10px;border-radius:999px;background:var(--panel2);color:#dbe7ff;font-size:13px}}.ticker{{color:var(--green);border:1px solid rgba(137,247,165,.35)}}.rec{{color:var(--yellow);border:1px solid rgba(255,224,138,.35)}}.conf{{color:var(--accent)}}.notice{{background:rgba(255,224,138,.1);border:1px solid rgba(255,224,138,.25);border-radius:14px;padding:14px;color:#fff0be}}footer{{color:var(--muted);text-align:center;padding:22px}}</style></head><body><header><h1>Daily Stock Info Dashboard</h1><div class="subtitle">유튜버 · 블로그 · 뉴스 취합 리포트 / 생성: {generated}</div></header><nav class="tabs"><a href="#domestic">국내</a><a href="#global">해외</a></nav><main><div class="notice">정보 취합/요약용입니다. 투자 판단은 본인 책임이며, 종목 언급은 추천·자문이 아니라 출처 기반 신호로 표시합니다.</div>{section('domestic',items)}{section('global',items)}</main><footer>Generated by Hermes Stock Info Agent</footer></body></html>'''
    OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(doc,encoding='utf-8'); print(f'Wrote {OUT} with {len(items)} items')
if __name__=='__main__': main()
