#!/usr/bin/env python3
"""Pre-build check for stock dashboard ImageGen2 cardnews assets.

Important: this script must NOT create synthetic/local fallback images. The user
requires public cardnews images to be generated by ImageGen2 only. If ImageGen2
fails after the cron retry policy, the failed/stale PNG is deleted and the HTML
must omit that cardnews image rather than reusing an old asset.

This pre-build step therefore reports missing/undersized assets as warnings, not
as a CI blocker. The post-build dashboard harness verifies that any successful
asset is large enough and referenced, while missing assets are omitted from HTML.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MIN_BYTES = 100_000
PROMPTS = ROOT / "data" / "imagegen2" / "cardnews_prompts.json"
REQUIRED_REGIONS = {"domestic", "global"}


def fail(message: str) -> None:
    print(f"IMAGEGEN2_ASSET_GATE_FAIL: {message}", file=sys.stderr)
    sys.exit(1)


def load_specs() -> list[dict]:
    if not PROMPTS.exists():
        fail(f"missing prompt spec file: {PROMPTS.relative_to(ROOT)}")
    raw = json.loads(PROMPTS.read_text(encoding="utf-8"))
    if isinstance(raw, dict):
        raw = raw.get("specs", [])
    if not isinstance(raw, list):
        fail("cardnews_prompts.json must be a list or {'specs': [...]} object")
    specs = [x for x in raw if isinstance(x, dict) and x.get("asset_path")]
    regions = {x.get("region") for x in specs}
    missing_regions = REQUIRED_REGIONS - regions
    if missing_regions:
        fail(f"missing ImageGen2 prompt specs for regions: {sorted(missing_regions)}")
    return specs


def main() -> None:
    ok: list[dict] = []
    failures: list[dict] = []
    for spec in load_specs():
        region = spec.get("region")
        if region not in REQUIRED_REGIONS:
            continue
        asset_path = str(spec["asset_path"])
        asset = Path(asset_path)
        if not asset.is_absolute():
            asset = ROOT / asset
        exists = asset.exists()
        size = asset.stat().st_size if exists else 0
        record = {
            "region": region,
            "asset_path": str(asset.relative_to(ROOT) if asset.is_relative_to(ROOT) else asset),
            "size": size,
            "prompt_present": bool(spec.get("prompt")),
        }
        if not exists or size < MIN_BYTES:
            failures.append(record)
        else:
            ok.append(record)
    status = "PASS" if not failures else "WARN"
    if failures:
        print(
            "IMAGEGEN2_ASSET_GATE_WARN: ImageGen2 PNG missing/undersized; "
            "stale assets must stay deleted and the renderer must omit them: "
            f"{json.dumps(failures, ensure_ascii=False)}",
            file=sys.stderr,
        )
    print(json.dumps({"status": status, "source": "ImageGen2 required when available", "ok": ok, "missing_or_omitted": failures, "min_bytes": MIN_BYTES}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
